services:
 pequeno_bot:
    build: .
    container_name: pequeno_bot
    restart: unless-stopped
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ME=${CHAT_ME}          # Chat donde el bot enviar치 mensajes de estado
      - CHAT_TARGET=${CHAT_TARGET}  # Chat objetivo donde el bot enviar치 contenido
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB} # Tama침o m치ximo de archivo en MB
      - LOG_LEVEL=${LOG_LEVEL}        # Nivel de logging
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ${DOWNLOADS_DIR}:/app/downloads
    networks:
      - pequeno-bot-net

networks:
  pequeno-bot-net:
    driver: bridge